# Generated by Django 5.1.3 on 2025-01-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('descriptions', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.URLField(blank=True)),
                ('year', models.IntegerField()),
                ('horse_power', models.IntegerField()),
                ('korobka', models.CharField(choices=[('avtomat', 'avtomat'), ('mexanika', 'mexanika')], max_length=250)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.brand')),
            ],
        ),
    ]
